/*
 * Copyright 2026 The Forbric Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.forbric.kernel.runtime;

import java.util.Map;

import it.unimi.dsi.fastutil.ints.AbstractInt2ObjectMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import it.unimi.dsi.fastutil.objects.ObjectSet;
import it.unimi.dsi.fastutil.objects.ObjectOpenHashSet;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.particles.ParticleType;
import net.minecraft.resources.ResourceLocation;

/**
 * An {@code Int2ObjectMap} face on the {@code ResourceLocation}-keyed particle-provider map, translating through
 * the particle registry.
 *
 * <p>On 26.2 this existed to keep the vanilla-typed and NeoForge-typed halves of one field one map: vanilla
 * declared {@code providers} as {@code Int2ObjectMap<ParticleProvider<?>>}, NeoForge 26.2 RE-TYPED the same
 * field to {@code Map<Identifier, ParticleProvider<?>>}, and the merged base carried BOTH (same name, different
 * descriptor is legal in the JVM) with only NeoForge's written. fabric-api's
 * {@code DirectParticleProviderRegistry.register} reads the field directly as an {@code Int2ObjectMap}, so the
 * kernel gave the vanilla-typed field this live view.
 *
 * <p><b>PORT(1.21.1):</b> that two-field split does not exist here. {@code javap -p} on the staged
 * {@code patched-mc-merged-1.21.1.jar} shows {@code ParticleEngine} declaring {@code providers} exactly once, as
 * {@code java.util.Map<ResourceLocation, ParticleProvider<?>>} — the shape both 1.21.1 families ship — and no
 * {@code Int2ObjectMap} field anywhere in the class. The view is still the right translation (fabric-api
 * 0.116.17's {@code ParticleManagerAccessor.getFactories()} is declared
 * {@code Int2ObjectMap<ParticleProvider<?>>} and remaps to {@code field_3835:Lit/unimi/dsi/fastutil/ints/Int2ObjectMap;}),
 * but there is no vanilla-typed field to install it into: {@code ForbricMergedBaseCompatTransformer}'s 26.2
 * write-side splice (a {@code PUTFIELD providers} pairing a second field) has no anchor, and writing this view
 * into the single surviving field would break every {@code ResourceLocation}-keyed reader. The 1.21.1 fix is a
 * READ-side redirect of fabric's accessor onto this method instead — a boot-side re-derivation, recorded for W5.
 *
 * <p>The view holds the live map BY REFERENCE, which is sound because the field is {@code final} and has exactly
 * one {@code PUTFIELD} in the whole class, in {@code <init>}; nothing, reload included, replaces it.
 */
public final class KernelParticleProviders {

	private KernelParticleProviders() {
	}

	/**
	 * Wraps the {@code ResourceLocation}-keyed provider map as an {@code Int2ObjectMap}.
	 *
	 * <p>Declared as {@code Object} on purpose. Every game-side seam in {@link net.forbric.kernel.runtime} is
	 * expressed in JDK types so {@code KernelRuntimeClasses} can state its signature without the boot side
	 * needing the game's libraries on its classpath; the caller is generated bytecode, which supplies its own
	 * {@code CHECKCAST}.
	 */
	public static Object intKeyedView(Map<?, ?> byName) {
		@SuppressWarnings("unchecked")
		Map<ResourceLocation, Object> live = (Map<ResourceLocation, Object>) byName;
		return new IntKeyedView(live);
	}

	/**
	 * An {@code Int2ObjectMap} face on a {@code ResourceLocation}-keyed map, translating through the particle
	 * registry.
	 *
	 * <p>Deliberately not spelled with its nested name anywhere in {@code src/main}: the registry test scans for
	 * {@code net.forbric.kernel.runtime.<Name>} and would then demand its own entry for this class.
	 */
	static final class IntKeyedView extends AbstractInt2ObjectMap<Object> {
		private static final long serialVersionUID = 1L;

		private final Map<ResourceLocation, Object> byName;
		/**
		 * Entries whose int key names no registered particle type. They cannot be translated, and dropping them
		 * would lose a registration silently; they live here instead, readable through this face only.
		 */
		private final Int2ObjectOpenHashMap<Object> untranslatable = new Int2ObjectOpenHashMap<>();
		private boolean warned;

		IntKeyedView(Map<ResourceLocation, Object> byName) {
			this.byName = byName;
		}

		private ResourceLocation key(int id) {
			ParticleType<?> type = BuiltInRegistries.PARTICLE_TYPE.byId(id);
			return type == null ? null : BuiltInRegistries.PARTICLE_TYPE.getKey(type);
		}

		@Override
		public Object get(int id) {
			ResourceLocation key = key(id);
			return key == null ? untranslatable.get(id) : byName.get(key);
		}

		@Override
		public Object put(int id, Object provider) {
			ResourceLocation key = key(id);
			if (key == null) {
				// byId answers null for an id no particle type holds. Keeping the entry beats losing it: the
				// caller would see a successful put either way, and a lost provider is a particle that never
				// renders with nothing said about it.
				if (!warned) {
					warned = true;
					System.out.println("[Forbric/Particles] a provider was registered under particle id " + id
							+ ", which no registered particle type holds — kept, but nothing reading the "
							+ "ResourceLocation-keyed map will see it");
				}
				return untranslatable.put(id, provider);
			}
			return byName.put(key, provider);
		}

		@Override
		public boolean containsKey(int id) {
			ResourceLocation key = key(id);
			return key == null ? untranslatable.containsKey(id) : byName.containsKey(key);
		}

		@Override
		public Object remove(int id) {
			ResourceLocation key = key(id);
			return key == null ? untranslatable.remove(id) : byName.remove(key);
		}

		@Override
		public int size() {
			return byName.size() + untranslatable.size();
		}

		/**
		 * Iteration translates back the other way. Particle ids are assigned when the built-in registry freezes at
		 * bootstrap, long before {@code Minecraft.<init>}, so the round trip is stable by the time anything here
		 * runs; an entry whose {@code ResourceLocation} is no longer registered is skipped rather than reported as
		 * id 0.
		 *
		 * <p>{@code PORT(1.21.1)}: 26.2's {@code Registry.getValue} became {@code Registry.get(ResourceLocation)},
		 * which on the {@code DefaultedRegistry} behind {@code BuiltInRegistries.PARTICLE_TYPE} answers the
		 * default rather than null. {@code getOptional} keeps the "skip what is not there" reading this asks for.
		 */
		@Override
		public ObjectSet<Int2ObjectMap.Entry<Object>> int2ObjectEntrySet() {
			ObjectSet<Int2ObjectMap.Entry<Object>> out = new ObjectOpenHashSet<>();
			for (Map.Entry<ResourceLocation, Object> e : byName.entrySet()) {
				ParticleType<?> type = BuiltInRegistries.PARTICLE_TYPE.getOptional(e.getKey()).orElse(null);
				if (type == null) continue;
				out.add(new AbstractInt2ObjectMap.BasicEntry<>(
						BuiltInRegistries.PARTICLE_TYPE.getId(type), e.getValue()));
			}
			for (Int2ObjectMap.Entry<Object> e : untranslatable.int2ObjectEntrySet()) {
				out.add(new AbstractInt2ObjectMap.BasicEntry<>(e.getIntKey(), e.getValue()));
			}
			return out;
		}
	}
}
